spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quizServiceDb
    username: sauravS
    password: saurav@jha24
  jpa:
    hibernate:
      ddl-auto: update
      connection:
        provider_disables_autocommit: true
      jdbc:
        time_zone: UTC
    show-sql: false